export const VOICES = [
  { id: "zh-CN-XiaoxiaoNeural", name: "晓晓 Xiaoxiao", locale: "zh-CN", language: "Chinese", gender: "Female", description: "温柔" },
  { id: "zh-CN-YunxiNeural", name: "云希 Yunxi", locale: "zh-CN", language: "Chinese", gender: "Male", description: "清朗" },
  { id: "zh-CN-YunyangNeural", name: "云扬 Yunyang", locale: "zh-CN", language: "Chinese", gender: "Male", description: "阳光" },
  { id: "zh-CN-XiaoyiNeural", name: "晓伊 Xiaoyi", locale: "zh-CN", language: "Chinese", gender: "Female", description: "甜美" },
  { id: "zh-CN-YunjianNeural", name: "云健 Yunjian", locale: "zh-CN", language: "Chinese", gender: "Male", description: "稳重" },
  { id: "zh-CN-XiaochenNeural", name: "晓辰 Xiaochen", locale: "zh-CN", language: "Chinese", gender: "Female", description: "知性" },
  { id: "zh-CN-XiaohanNeural", name: "晓涵 Xiaohan", locale: "zh-CN", language: "Chinese", gender: "Female", description: "优雅" },
  { id: "zh-CN-XiaomengNeural", name: "晓梦 Xiaomeng", locale: "zh-CN", language: "Chinese", gender: "Female", description: "梦幻" },
  { id: "zh-CN-XiaomoNeural", name: "晓墨 Xiaomo", locale: "zh-CN", language: "Chinese", gender: "Female", description: "文艺" },
  { id: "zh-CN-XiaoqiuNeural", name: "晓秋 Xiaoqiu", locale: "zh-CN", language: "Chinese", gender: "Female", description: "成熟" },
  { id: "zh-CN-XiaoruiNeural", name: "晓睿 Xiaorui", locale: "zh-CN", language: "Chinese", gender: "Female", description: "智慧" },
  { id: "zh-CN-XiaoshuangNeural", name: "晓双 Xiaoshuang", locale: "zh-CN", language: "Chinese", gender: "Female", description: "活泼" },
  { id: "zh-CN-XiaoxuanNeural", name: "晓萱 Xiaoxuan", locale: "zh-CN", language: "Chinese", gender: "Female", description: "清新" },
  { id: "zh-CN-XiaoyanNeural", name: "晓颜 Xiaoyan", locale: "zh-CN", language: "Chinese", gender: "Female", description: "柔美" },
  { id: "zh-CN-XiaoyouNeural", name: "晓悠 Xiaoyou", locale: "zh-CN", language: "Chinese", gender: "Female", description: "悠扬" },
  { id: "zh-CN-XiaozhenNeural", name: "晓甄 Xiaozhen", locale: "zh-CN", language: "Chinese", gender: "Female", description: "端庄" },
  { id: "zh-CN-YunfengNeural", name: "云枫 Yunfeng", locale: "zh-CN", language: "Chinese", gender: "Male", description: "磁性" },
  { id: "zh-CN-YunhaoNeural", name: "云皓 Yunhao", locale: "zh-CN", language: "Chinese", gender: "Male", description: "豪迈" },
  { id: "zh-CN-YunxiaNeural", name: "云夏 Yunxia", locale: "zh-CN", language: "Chinese", gender: "Male", description: "热情" },
  { id: "zh-CN-YunyeNeural", name: "云野 Yunye", locale: "zh-CN", language: "Chinese", gender: "Male", description: "野性" },
  { id: "zh-CN-YunzeNeural", name: "云泽 Yunze", locale: "zh-CN", language: "Chinese", gender: "Male", description: "深沉" },
  { id: "en-US-JennyNeural", name: "Jenny", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-GuyNeural", name: "Guy", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-AriaNeural", name: "Aria", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-DavisNeural", name: "Davis", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-AmberNeural", name: "Amber", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-AnaNeural", name: "Ana", locale: "en-US", language: "English", gender: "Female", description: "Child, US" },
  { id: "en-US-AndrewNeural", name: "Andrew", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-AshleyNeural", name: "Ashley", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-BrandonNeural", name: "Brandon", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-ChristopherNeural", name: "Christopher", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-CoraNeural", name: "Cora", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-ElizabethNeural", name: "Elizabeth", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-EricNeural", name: "Eric", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-JacobNeural", name: "Jacob", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-JaneNeural", name: "Jane", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-JasonNeural", name: "Jason", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-MichelleNeural", name: "Michelle", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-MonicaNeural", name: "Monica", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-NancyNeural", name: "Nancy", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-RogerNeural", name: "Roger", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-SaraNeural", name: "Sara", locale: "en-US", language: "English", gender: "Female", description: "US" },
  { id: "en-US-SteffanNeural", name: "Steffan", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-US-TonyNeural", name: "Tony", locale: "en-US", language: "English", gender: "Male", description: "US" },
  { id: "en-GB-SoniaNeural", name: "Sonia", locale: "en-GB", language: "English", gender: "Female", description: "UK" },
  { id: "en-GB-RyanNeural", name: "Ryan", locale: "en-GB", language: "English", gender: "Male", description: "UK" },
  { id: "en-GB-LibbyNeural", name: "Libby", locale: "en-GB", language: "English", gender: "Female", description: "UK" },
  { id: "en-GB-MaisieNeural", name: "Maisie", locale: "en-GB", language: "English", gender: "Female", description: "Child, UK" },
  { id: "en-AU-NatashaNeural", name: "Natasha", locale: "en-AU", language: "English", gender: "Female", description: "AU" },
  { id: "en-AU-WilliamNeural", name: "William", locale: "en-AU", language: "English", gender: "Male", description: "AU" },
  { id: "ja-JP-NanamiNeural", name: "Nanami 七海", locale: "ja-JP", language: "Japanese", gender: "Female", description: "" },
  { id: "ja-JP-KeitaNeural", name: "Keita 圭太", locale: "ja-JP", language: "Japanese", gender: "Male", description: "" },
  { id: "ja-JP-AoiNeural", name: "Aoi 葵", locale: "ja-JP", language: "Japanese", gender: "Female", description: "" },
  { id: "ja-JP-DaichiNeural", name: "Daichi 大地", locale: "ja-JP", language: "Japanese", gender: "Male", description: "" },
  { id: "ja-JP-MayuNeural", name: "Mayu 真由", locale: "ja-JP", language: "Japanese", gender: "Female", description: "" },
  { id: "ja-JP-NaokiNeural", name: "Naoki 直樹", locale: "ja-JP", language: "Japanese", gender: "Male", description: "" },
  { id: "ja-JP-ShioriNeural", name: "Shiori 栞", locale: "ja-JP", language: "Japanese", gender: "Female", description: "" },
  { id: "ko-KR-SunHiNeural", name: "SunHi 선희", locale: "ko-KR", language: "Korean", gender: "Female", description: "" },
  { id: "ko-KR-InJoonNeural", name: "InJoon 인준", locale: "ko-KR", language: "Korean", gender: "Male", description: "" },
  { id: "ko-KR-BongJinNeural", name: "BongJin 봉진", locale: "ko-KR", language: "Korean", gender: "Male", description: "" },
  { id: "ko-KR-GookMinNeural", name: "GookMin 국민", locale: "ko-KR", language: "Korean", gender: "Male", description: "" },
  { id: "ko-KR-JiMinNeural", name: "JiMin 지민", locale: "ko-KR", language: "Korean", gender: "Female", description: "" },
  { id: "ko-KR-SeoHyeonNeural", name: "SeoHyeon 서현", locale: "ko-KR", language: "Korean", gender: "Female", description: "" },
  { id: "ko-KR-SoonBokNeural", name: "SoonBok 순복", locale: "ko-KR", language: "Korean", gender: "Female", description: "" },
  { id: "ko-KR-YuJinNeural", name: "YuJin 유진", locale: "ko-KR", language: "Korean", gender: "Female", description: "" },
  { id: "fr-FR-DeniseNeural", name: "Denise", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-HenriNeural", name: "Henri", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-EloiseNeural", name: "Eloise", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-AlainNeural", name: "Alain", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-BrigitteNeural", name: "Brigitte", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-CelesteNeural", name: "Celeste", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-ClaudeNeural", name: "Claude", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-CoraliNeural", name: "Corali", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-JacquelineNeural", name: "Jacqueline", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-JeromeNeural", name: "Jerome", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-JosephineNeural", name: "Josephine", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "fr-FR-MauriceNeural", name: "Maurice", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-YvesNeural", name: "Yves", locale: "fr-FR", language: "French", gender: "Male", description: "" },
  { id: "fr-FR-YvetteNeural", name: "Yvette", locale: "fr-FR", language: "French", gender: "Female", description: "" },
  { id: "de-DE-KatjaNeural", name: "Katja", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-ConradNeural", name: "Conrad", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-AmalaNeural", name: "Amala", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-BerndNeural", name: "Bernd", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-ChristophNeural", name: "Christoph", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-ElkeNeural", name: "Elke", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-GiselaNeural", name: "Gisela", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-KasperNeural", name: "Kasper", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-KillianNeural", name: "Killian", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-KlarissaNeural", name: "Klarissa", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-KlausNeural", name: "Klaus", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-LouisaNeural", name: "Louisa", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-MajaNeural", name: "Maja", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "de-DE-RalfNeural", name: "Ralf", locale: "de-DE", language: "German", gender: "Male", description: "" },
  { id: "de-DE-TanjaNeural", name: "Tanja", locale: "de-DE", language: "German", gender: "Female", description: "" },
  { id: "es-ES-ElviraNeural", name: "Elvira", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-AlvaroNeural", name: "Alvaro", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-AbrilNeural", name: "Abril", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-ArnauNeural", name: "Arnau", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-DarioNeural", name: "Dario", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-EliasNeural", name: "Elias", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-EstrellaNeural", name: "Estrella", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-IreneNeural", name: "Irene", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-LaiaNeural", name: "Laia", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-LiaNeural", name: "Lia", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-NilNeural", name: "Nil", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-SaulNeural", name: "Saul", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-TeoNeural", name: "Teo", locale: "es-ES", language: "Spanish", gender: "Male", description: "" },
  { id: "es-ES-TrianaNeural", name: "Triana", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-ES-VeraNeural", name: "Vera", locale: "es-ES", language: "Spanish", gender: "Female", description: "" },
  { id: "es-MX-DaliaNeural", name: "Dalia", locale: "es-MX", language: "Spanish", gender: "Female", description: "MX" },
  { id: "es-MX-JorgeNeural", name: "Jorge", locale: "es-MX", language: "Spanish", gender: "Male", description: "MX" },
  { id: "ru-RU-SvetlanaNeural", name: "Svetlana Светлана", locale: "ru-RU", language: "Russian", gender: "Female", description: "" },
  { id: "ru-RU-DmitryNeural", name: "Dmitry Дмитрий", locale: "ru-RU", language: "Russian", gender: "Male", description: "" },
  { id: "ru-RU-DariyaNeural", name: "Dariya Дарья", locale: "ru-RU", language: "Russian", gender: "Female", description: "" }
    ];
